name: "Test actions"
description: "Test action.yml file"
inputs:
   names:
     required: true
     description: "user named value here"

branding:
  icon: 'award'
  color: 'cyan'

runs:
  using: "composite"
  steps:
    - uses: action/checkout@v2
      run: echo "Value of the name is:  "${{ inputs.names }}

