on: [push]

jobs:
  workflow:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Write a multi-line message
        run: |
          echo This is a demo workflow.
          echo ho very basic and easy-to-understand workflow.
