name: deploy to development
run-name: PipeLine started by ${{ github.actor }}
on:
  pull_request:
    branches: 
      - develop
    types: [closed]
    
jobs:
  ssh-test:
    name: deploy
    runs-on: ubuntu-latest
    steps:
     - name: copy env files
       run: echo ${{ secrets.ENV_DEV }} > test-file
     - name: Copy single file to remote
       uses: garygrossgarten/github-action-scp@release
       with:
          local: test-file
          remote: /opt/test-file
          host: 23.23.146.36
          username: root
          privateKey: ${{ secrets.AWS_KEY_WOLO }}
