name: test
run-name: PipeLine started by ${{ github.actor }}
on: [push]

env:
   GITHUB_REPOSITORY: ${{ github.repository }}
   GITHUB_REF_NAME: ${{ github.ref_name }}

jobs:
  Build-Step:
    name: build
    runs-on: weartec-runner
    steps:
     - uses: actions/checkout@v2
     - run: .infra-script/build.sh

  Push-Step:
    name: push
    runs-on: weartec-runner
    steps:
     - uses: actions/checkout@v2
     - run: .infra-script/push.sh
       env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ECR_LOGIN_PASSWORD: ${{ secrets.ECR_LOGIN_PASSWORD }}
        ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}
