name: build
run-name: PipeLine started by ${{ github.actor }}
on: [push]

env:
  resourceGroup1: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
  resourceGroup2: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  Build-Step:
    name: deploy
    runs-on: github-runner
    steps:
     - uses: actions/checkout@v2
     - run: |
        echo ${{ env.resourceGroup1 }}
        echo ${{ env.resourceGroup2 }}
 #         echo ${{ env.GITHUB_REPOSITORY }}
 #         docker  build -t ${{ env.GITHUB_REPOSITORY }}:latest -f Dockerfile-dev .
 #         docker images
 #
 #  Push-Step:
 #    name: deploy
 #    runs-on: github-runner
 #    steps:
 #     - uses: actions/checkout@v2
 #     - run: |
 #        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 #        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_LOGIN_PASSWORD }}
 #        docker tag ${{ GITHUB_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY_URL }}:${{ GITHUB_REF_NAME }}
 #        docker push ${{ secrets.ECR_REPOSITORY_URL }}:${{ GITHUB_REF_NAME }}
 #        docker image prune -f
 #
