name: deploy test
run-name: deploy test by ${{ github.actor }}
on: [push]
jobs:
  ssh-test:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Testing ssh
      uses: appleboy/ssh-action@master
      with:
        host: 23.23.146.36
        username: ubuntu
        key: ${{ secrets.AWS_KEY_WOLO }}
        port: 22
        script: |
           cd /opt 
           ls
           pwd
