name: test
run-name: PipeLine started by ${{ github.actor }}
on: [push]

env:
 ENV_DEV: ${{ secrets.ENV_DEV }}
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 ECR_LOGIN_PASSWORD: ${{ secrets.ECR_LOGIN_PASSWORD }}
 ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}
 GITHUB_REF_NAME: ${{ github.ref_name }}
 GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  Build-Step:
    name: build
    runs-on: weartec-runner
    steps:
     - uses: actions/checkout@v3
     - run: |
         echo -n $ENV_DEV > .env.development
         ls -lah
         cat .env.development
#        .infra-script/build.sh

#   Push-Step:
#     name: push
#     runs-on: weartec-runner
#     needs: Build-Step
#     steps:
#      - uses: actions/checkout@v3
#      - run: .infra-script/push.sh

