name: deploy to development
run-name: PipeLine started by ${{ github.actor }}
on:
  push:
    branches:
      - "*"
      
jobs:
  test:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{secrets.TEST_ENV}} | base > .env.development
          cat .env.development
