name: deploy test
run-name: Pipeline started by ${{ github.actor }}
on:
  workflow_run:
    workflows: ["Build"]
    branches:
      - test-branch
jobs:
  ssh-test:

    name: deploy
    runs-on: ubuntu-latest
    steps:
 #     - name: Testing SSh
 #       uses: garygrossgarten/github-action-ssh@release
 #       with:
 #         command: |
 #            pwd
 #            cd /opt
 #            ls -lah
 #         host: 23.23.146.36
 #         username: ubuntu
 #         privateKey: ${{ secrets.AWS_KEY_WOLO }}

#     - name: check out repository code 
#       uses: actions/checkout@v3
#
#     - name: use script command
#       run : |
#         echo ${{ secrets.ENV_DEV }} | sed -e 's/\(.\)/\1 /g'
#         ls
#         cat newfile
     - name: copy env files
       run: echo ${{ secrets.ENV_DEV }} > test-file
     - name: Copy single file to remote
       uses: garygrossgarten/github-action-scp@release
       with:
          local: test-file
          remote: /opt/test-file
          host: 23.23.146.36
          username: root
          privateKey: ${{ secrets.AWS_KEY_WOLO }}
