name: deploy to development
run-name: PipeLine started by ${{ github.actor }}
on: push

#jobs:
#  ssh-test:
#    name: deploy
#    runs-on: ubuntu-latest
#    steps:
#     - name: copy env files
#       run: echo ${{ secrets.ENV_DEV }} > test-file
#     - name: Copy single file to remote
#       uses: garygrossgarten/github-action-scp@release
#       with:
#          local: test-file
#          remote: /opt/test-file
#          host: 23.23.146.36
#          username: root
#          privateKey: ${{ secrets.AWS_KEY_WOLO }}

jobs:
  deploy:
    name: rsync
    runs-on: ubuntu-latest
    steps:
    - name: copy env files
      run: |
       pwd
       echo ${{ secrets.ENV_DEV }} > test-file
       ls
    - uses: actions/checkout@v2
    - name: rsync deployment
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: /home/runner/work/react-app/react-app/test-file
        remote_path: /opt/test-file
        remote_host: 23.23.146.36
        remote_user: root
        remote_key: ${{ secrets.AWS_KEY_WOLO }}
        
