name: Test
run-name: PipeLine started by ${{ github.actor }}
on: push

jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setting the value
        uses: ./.github/actions
        with:
           names: ujan
