name: deploy test
run-name: Pipeline started by ${{ github.actor }}
on: [push]
jobs:
  ssh-test:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Testing ssh
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 23.23.146.36
        username: root
        key: ${{ secrets.AWS_KEY_WOLO }}
        port: 22
        script: whoami
