name: Test
run-name: PipeLine started by ${{ github.actor }}
on: push

jobs:
  deploy:
    name: rsync
#   runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=red" >> $GITHUB_ENV
          echo "${{ env.action_state }}" 
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'red'
