name: deploy test
run-name: Pipeline started by ${{ github.actor }}
on: [push]
jobs:
  ssh-test:
    name: deploy
    runs-on: ubuntu-latest
    steps:
 #     - name: Testing SSh
 #       uses: garygrossgarten/github-action-ssh@release
 #       with:
 #         command: |
 #            pwd
 #            cd /opt
 #            ls -lah
 #         host: 23.23.146.36
 #         username: ubuntu
 #         privateKey: ${{ secrets.AWS_KEY_WOLO }}

     - name: check out repository code 
       uses: actions/checkout@test-branch

     - name: use script command
       env:
         env-file:  ${{ secrets.ENV_DEV }} 
       run : |
         echo $env-file               
